# Site settings
title: Resources
name: Year4000

description: >
  Resources for Year4000, here is documentation on how various features work on
  the Year4000 Network.

url: "https://resources.year4000.net"
#url: "http://localhost:4000"

twitter_username: Y4KNetwork

# Build settings
markdown: kramdown

# Collections
collections:
  mapnodes:
    name: MapNodes
    output: true
    permalink: /mapnodes/:path/
  locales:
    name: Locales
    output: true
    permalink: /locales/:path/
